doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
        options:
            !php/const PDO::MYSQL_ATTR_INIT_COMMAND: "SET @@SESSION.innodb_ft_enable_stopword = 'OFF';"
    orm:
        dql:
            string_functions:
                LEVENSHTEIN: App\DoctrineExtensions\LevenshteinFunction
                least: DoctrineExtensions\Query\Mysql\Least
                greatest: DoctrineExtensions\Query\Mysql\Greatest
                MATCH: DoctrineExtensions\Query\Mysql\MatchAgainst
                MATCH_AGAINST: DoctrineExtensions\Query\Mysql\MatchAgainst
                SOUNDEX: DoctrineExtensions\Query\Mysql\Soundex
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        dbal:
            logging: '%kernel.debug%'
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
