# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $telegramLogger: '@monolog.logger.telegram'
            $ffmpegLogger: '@monolog.logger.ffmpeg'
            $webhookSecret: '%env(TELEGRAM_WEBHOOK_SECRET)%'
            $storageChatId: '%env(int:TELEGRAM_STORAGE_CHAT_ID)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Telegram\TelegramService:
        arguments:
            $apiKey: '%env(TELEGRAM_BOT_TOKEN)%'
            $botName: '%env(TELEGRAM_BOT_USERNAME)%'

    App\Service\Telegram\VoiceSender:
        arguments:
            $publicDir: '%kernel.project_dir%/public'

    App\Command\ImportAudioCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
