version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MARIADB_VERSION:-10.8}
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-kntntbot}
      # You should definitely change the password in production
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
    volumes:
      - database_data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
